[id='creating-a-workbench']
= Creating a workbench and selecting a workbench image

A workbench is an instance of your development and experimentation environment. When you create a workbench, you select a workbench image that is optimized with the tools and libraries that you need for developing models. 

.Prerequisites

* You created a `My Storage` connection as described in xref:storing-data-with-connections.adoc[Storing data with connections].

* If you intend to complete the pipelines section of this {deliverable}, you configured a pipeline server as described in xref:enabling-data-science-pipelines.adoc[Enabling data science pipelines].


.Procedure

. Navigate to the project detail page for the data science project that you created in xref:setting-up-your-data-science-project.adoc[Setting up your data science project].

. Click the *Workbenches* tab, and then click the *Create workbench* button.

. Fill out the name and description.

. Select the latest *Tensorflow* image for successful completion of this tutorial.

IMPORTANT: If you do not choose the latest *Tensorflow* image, upcoming code executions will fail.

. Choose a **small** deployment.

. If your OpenShift cluster has available GPUs, the *Create workbench* form includes an *Accelerator* option. Select *None*. This {deliverable} does not require any GPUs.

. Leave the default environment variables and storage options.

. For *Connections*, click *Attach existing connection*.

. Select `My Storage` and then click *Attach*.

. Click *Create workbench*.

.Verification

In the *Workbenches* tab for the project, the status of the workbench changes from `Starting` to `Running`.

NOTE: If you made a mistake, you can easily edit the workbench.

.Next step

xref:importing-files-into-jupyter.adoc[Importing the {deliverable} files into the JupyterLab environment]
