[id='deploying-a-model-single-model-server']
= Deploying on a single-model server

You can deploy your model on a single-model server. 

.Prerequisites

* A user with `admin` privileges has enabled the single-model serving option on your OpenShift cluster.

.Procedure

. In the {productname-short} dashboard, navigate to the project details page and click the *Models* tab.
NOTE: Depending on how model serving has been configured on your cluster, you might see only one model serving option.

. In the *Single-model serving platform* tile, click *Select single-model*.
. In the form, provide the following values:
.. For *Model deployment name*, type `fraud`.
.. For *Serving runtime*, select `OpenVINO Model Server`.
.. For *Model framework (name - version)*, select `onnx-1`.
.. For *Deployment mode*, select `Advanced`.
.. For *Existing connection*, select `My Storage`.
.. Type the path that leads to the version folder that contains your model file: `models/fraud`
.. Leave the other fields with the default settings.

. Click *Deploy*.

.Verification

Notice the loading symbol under the *Status* section. The symbol changes to a green checkmark when the deployment is successful.

.Next step

xref:testing-the-model-api.adoc[Testing the model API]
