[id='deploying-a-model-multi-model-server']
= Deploying a model on a multi-model server

{productname-short} multi-model servers can host several models at once. You create a new model server and deploy your model to it.

.Prerequisites

* A user with `admin` privileges has enabled the multi-model serving platform on your OpenShift cluster.

.Procedure

. In the {productname-short} dashboard, navigate to the project details page and click the *Models* tab.

NOTE: Depending on how model serving has been configured on your cluster, you might see only one model serving platform option.

. In the *Multi-model serving platform* tile, click *Select multi-model*.

. In the form, provide the following values:
.. For *Model server name*, type a name, for example `Model Server`.
.. For *Serving runtime*, select `OpenVINO Model Server`.
.. Leave the other fields with the default settings.
. Click *Add*.
. In the *Models and model servers* list, next to the new model server, click *Deploy model*.

. In the form, provide the following values:
.. For *Model deployment name*, type `fraud`.
.. For *Model framework (name - version)*, select `onnx-1`.
.. For *Existing connection*, select `My Storage`.
.. Type the path that leads to the version folder that contains your model file: `models/fraud`
.. Leave the other fields with the default settings.
. Click *Deploy*.

.Verification

Notice the loading symbol under the *Status* section. The symbol changes to a green checkmark when the deployment completes successfully. 

.Next step

xref:testing-the-model-api.adoc[Testing the model API]
