[id='importing-files-into-jupyter']
= Importing the {deliverable} files into the JupyterLab environment

:git-version: main

JupyterLab is a data science/machine learning IDE that is integrated with your *OpenShift* cluster. This integration enables interactive workflows within a robust, scalable and containerized environment.

.Prerequisites

* You created a workbench, as described in xref:creating-a-workbench.adoc[Creating a workbench and selecting a workbench image].

.Procedure

. Click the link for your workbench. If prompted, log in and enable JupyterLab authorization.

. Your JupyterLab environment window opens.
This window shows the files and folders that are saved inside your project in {productname-short}.

. Include this tutorial in your JupyterLab environment:

.. On the toolbar, click the *Git Clone* icon.

.. Enter the following {deliverable} Git *https* URL:
+
[.lines_space]
[.console-input]
[source,text]
----
https://github.com/rh-aiservices-bu/fraud-detection.git
----

.. Select the **Include submodules** option, and then click *Clone*.

.. In the left navigation, double-click the newly created *fraud-detection* folder.

.. Click the *Git* icon, and then *Current Branch* to expand the branches and tags selector panel.
... On the *Branches* tab, in the *Filter* field, enter *{git-version}*.

.. Select *origin/{git-version}*. 
+
The current branch changes to *{git-version}*.


.Verification

In the file browser, you should see all of the notebooks that you cloned from Git.

.Additional resources
For more information see the following:
link:https://jupyter.org/[JupyterLab]

.Next step

xref:running-code-in-a-notebook.adoc[Running code in a notebook]

or

xref:training-a-model.adoc[Training a model]
