= Fraud Detection {deliverable} with {productname-long}
:page-layout: home
:!sectids:

[id='introduction']
[.text-center.strong]
== Introduction

Welcome. In this {deliverable}, you learn how to incorporate data science and artificial intelligence and machine learning (AI/ML) into an OpenShift development workflow.

You use an example fraud detection model to complete the following tasks in https://www.redhat.com/en/technologies/cloud-computing/openshift/openshift-ai[{productname-long}] without the need to install anything on your computer:

* Explore a pre-trained fraud detection model by using a Jupyter notebook.
* Deploy the model by using {productname-short} model serving.
* Refine and train the model by using automated pipelines.
* Learn how to train the model by using Ray, a distributed computing framework.

== About the example fraud detection model

The example fraud detection model monitors credit card transactions for potential fraudulent activity. It analyzes the following credit card transaction details:

* The geographical distance from the previous credit card transaction.
* The price of the current transaction, compared to the median price of all the user's transactions.
* Whether the user completed the transaction by using the hardware chip in the credit card, by entering a PIN number, or by making an online purchase.

Based on this data, the model outputs the likelihood of the transaction being fraudulent.

== Before you begin

You should have access to an OpenShift cluster where {productname-long} is installed. 

If don't have access to a cluster that includes an instance of {productname-short}, see the https://developers.redhat.com/products/red-hat-openshift-ai/download[{productname-long} page on the {org-name} Developer website]. There, you can create an account and access the https://console.redhat.com/openshift/sandbox[*free {org-name} Developer Sandbox*] or you can learn how to install {productname-short} on *your own OpenShift cluster*.


[IMPORTANT]
====
If your cluster uses self-signed certificates, before you begin the {deliverable}, your {productname-short} administrator must add self-signed certificates for {productname-short} as described in link:https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed/latest/html/installing_and_uninstalling_openshift_ai_self-managed/working-with-certificates_certs[Working with certificates^] (Self-Managed) or link:https://docs.redhat.com/en/documentation/red_hat_openshift_ai_cloud_service/1/html/installing_and_uninstalling_openshift_ai_cloud_service/working-with-certificates_certs[Working with certificates^] (Cloud Service).
====

If you're ready, xref:navigating-to-the-dashboard.adoc[start the {deliverable}].
