= Fraud Detection {deliverable} with {productname-long}
:page-layout: home
:!sectids:

[id='introduction']
[.text-center.strong]
== Introduction

:rhoai-version: main (the latest)
// for the downstream tutorial, change the value of rhoai-version to match the git-version value in the importing-files-into-jupyter.adoc file

[role="_abstract"]
Welcome! In this {deliverable}, you learn how to use data science, artificial intelligence (AI), and machine learning (ML) in an OpenShift development workflow.

You complete the following tasks in link:https://www.redhat.com/en/technologies/cloud-computing/openshift/openshift-ai[{productname-long}] without installing any software on your computer:

* Explore a pre-trained fraud detection model by using a Jupyter notebook.
* Deploy the model by using {productname-short} model serving.
* Refine and train the model by using automated pipelines.
* Learn how to train the model by using distributed computing frameworks.

== About the example fraud detection model

The example fraud detection model monitors credit card transactions for potential fraudulent activity. It analyzes the following credit card transaction details:

* The geographical distance from an earlier credit card transaction.
* The price of the current transaction, compared to the median price of all the transactions.
* Whether the user completed the transaction by using the hardware chip in the credit card, by entering a PIN number, or by making an online purchase.

Based on this data, the model outputs the likelihood of the transaction being fraudulent.

== Before you begin

You must have access to an OpenShift cluster which has {productname-long} installed.

NOTE: Due to resource constraints, this {rhoai-version} edition of the tutorial is not supported in the https://console.redhat.com/openshift/sandbox[*{org-name} Developer Sandbox*].

// commenting out Sandbox - 3.x not available there yet
//If you do not have access to a cluster that has an instance of {productname-short}, see the https://developers.redhat.com/products/red-hat-openshift-ai/download[{productname-long} page on the {org-name} Developer website]. There, you can create an account and access the https://console.redhat.com/openshift/sandbox[*free {org-name} Developer Sandbox*] or you can learn how to install {productname-short} on *your own OpenShift cluster*.

//NOTE: The _Distributing training jobs with the Training Operator_ section of this {deliverable} is not supported in the {org-name} Developer Sandbox.

[IMPORTANT]
====
If your cluster uses self-signed certificates, before you begin the {deliverable}, your {productname-short} administrator must add self-signed certificates for {productname-short} as described in link:https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed/latest/html/installing_and_uninstalling_openshift_ai_self-managed/working-with-certificates_certs[Working with certificates^] (Self-Managed).
====

//or link:https://docs.redhat.com/en/documentation/red_hat_openshift_ai_cloud_service/1/html/installing_and_uninstalling_openshift_ai_cloud_service/working-with-certificates_certs[Working with certificates^] (Cloud Service).

If you're ready, xref:navigating-to-the-dashboard.adoc[start the {deliverable}].
