[id='running-code-in-a-notebook']
= Running code in a notebook
A notebook is an environment where you have _cells_ that can display formatted text or code.

NOTE: If you are familiar with Jupyter, you can xref:training-a-model.adoc[skip to the next section].

Code cells are prepopulated with Python code that you can modify and run interactively. The code does not run on your computer or in the browser, but directly in *{productname-long}*.

You can run a code cell from the notebook interface or from the keyboard:

* *From the user interface:* Select the cell (by clicking inside the cell or to the left side of the cell) and then click *Run* from the toolbar.

* *From the keyboard:* Press `CTRL` + `ENTER` to run a cell or press `SHIFT` + `ENTER` to run the cell and automatically select the next one.

After you run a cell, you can see the result of its code as well as information about when the cell was executed.

When you save a notebook, the code and the results are saved too. You can reopen the notebook to look at the results without having to execute the program again.

Notebooks are so named because they are like a physical _notebook_. You can record observations and save code and parameters you have created. You can see the output of the experiment along with your notes. To view your notes, switch the cell type from `Code` to `Markdown.`

== Try Running your code
Now that you know the basics, give it a try.

.Prerequisites

* You have imported the {deliverable} files into your JupyterLab environment as described in 
xref:importing-files-into-jupyter.adoc[Importing the {deliverable} files into the JupyterLab environment].

.Procedure

. In your JupyterLab environment, locate the `0_sandbox.ipynb` file and double-click it to launch the notebook. The notebook opens in a new tab in the content section of the environment. 

. Experiment by running the existing cells, adding more cells and creating functions.

.. You can experiment freely, without the risk of breaking anything or impacting other users. 

. Optional:  Create a new notebook in which the code cells are run by using a Python 3 kernel:
.. Create a new notebook by either selecting *File ->New ->Notebook* or by clicking the Python 3 tile in the Notebook section of the launcher window:

.. You can use different kernels, with different languages or versions, to run in your notebook.

.Additional resources

To learn more about notebooks, visit https://jupyter.org/[the Jupyter site].

.Next step

xref:training-a-model.adoc[Training a model]
