[id='setting-up-your-data-science-project']
= Setting up your data science project

To implement a data science workflow, you must create a data science project. The project enables the following:

* Organization and collaboration on resources within separated namespaces. 
* Creating multiple workbenches with their own IDE environments.
* Workbenches that maintain their own connections and cluster storage.
* Workbenches that share models and data with pipelines and model servers.

.Prerequisites

* You have logged in to *{productname-long}*.

.Procedure

. On the navigation menu, select  *Data science projects*. All of your data science projects are listed here.

. *If you are using the {org-name} Developer Sandbox*, it provides a default data science project, `myname-dev`. Select it and skip to the *Verification* section below in this document.
+
*If you are using your own OpenShift cluster*, you can select an existing project or create a new one. Click *Create project*. 
+
NOTE: It is possible to start a Jupyter notebook by clicking the *Start basic workbench* button, selecting a notebook image, and clicking *Start server*. However, this would be a notebook that you could not reuse.

. In the *Create project* modal, enter a display name and description.

. Click *Create*.

.Verification

You can see your project's initial state. Individual tabs provide more information about the project components and project access permissions. See the following for more details about the tabs:

** *Workbenches* are instances of your development and experimentation environment. They typically contain IDEs, such as JupyterLab, RStudio, and Visual Studio Code.

** *Pipelines* contain the data science pipelines that are executed within the project.

** *Models* allow you to quickly serve a trained model for real-time inference. You can have multiple model servers per data science project. One model server can host multiple models.

** *Cluster storage* is a persistent volume that retains the files and data you are working on within a workbench. A workbench has access to one or more cluster storage instances.

** *Connections* contain configuration parameters that are required to connect to a data source, such as an S3 object bucket.

** *Permissions* define which users and groups can access the project.

.Next step

xref:storing-data-with-connections.adoc[Storing data with connections]
