[id='setting-up-kueue-resources']
= Setting up Kueue resources

In this section, you prepare your {deliverable} environment so that you can use Kueue for distributing training with the Training Operator. Kueue allows you to manage cluster resource quotas and specify how they are consumed.

NOTE: If you are using the Red Hat Developer Sandbox, or you do not intend to use Kueue, advance to: xref:creating-a-workbench.adoc[Creating a workbench and selecting a workbench image].

.Procedure

. In the {productname-short} dashboard, click the application launcher icon and then select the *OpenShift Console* option.

. In the OpenShift console, click *+* in the top navigation bar.

. Select your project from the list of projects.

. Verify that you selected the correct project.

. Copy the following code and paste it into the *Import YAML* editor.
+
[.lines_space]
[.console-input]
[source, yaml]
----
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: default-flavor
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: cluster-queue
spec:
  namespaceSelector: {}
  resourceGroups:
  - coveredResources: ["cpu", "memory"]
    flavors:
    - name: "default-flavor"
      resources:
      - name: "cpu"
        nominalQuota: 4
      - name: "memory"
        nominalQuota: 8Gi
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  name: local-queue
spec:
  clusterQueue: cluster-queue 
----

. Click *Create*.

.Verification

. In the OpenShift console, you should see a "Resources successfully created" message and the following resources listed:
+
* `default-flavor`
* `cluster-queue`
* `local-queue`

.Next step

xref:creating-a-workbench.adoc[Creating a workbench and selecting a notebook image]