[id='storing-data-with-connections']
= Storing data with connections

You can add connections to workbenches to join data inputs and object storage buckets. A connection is a resource that contains the configuration parameters needed to connect to a data source or data sink, such as an AWS S3 object storage bucket.

For this {deliverable}, you run a provided script that creates the following local MinIO storage buckets for you:

* *My Storage* - Use this bucket for storing your models and data. You can reuse this bucket and its connection for your notebooks and model servers.
*  *Pipelines Artifacts* - Use this bucket as storage for your pipeline artifacts. A pipeline artifacts bucket is required when you create a pipeline server. 

NOTE: It is possible to use one storage bucket for storing models, data, and pipeline artifacts. However, it is a best practice to keep your models and pipelines in separate buckets.

The provided script also creates a connection to each storage bucket. 

To run the script that installs local MinIO storage buckets and creates connections to them, follow the steps in xref:running-a-script-to-install-storage.adoc[Running a script to install local object storage buckets and create connections].

NOTE: If you want to use your own S3-compatible object storage buckets follow the steps in xref:creating-connections-to-storage.adoc[Creating connections to your own S3-compatible object storage].