:_module-type: CONCEPT

[id='storing-data-with-connections']
= Configure storage credentials

[role="_abstract"]
Add connections to workbenches to connect your project to data inputs and object storage buckets. A connection is a resource that has the configuration parameters needed to connect to a data source or data sink, such as an AWS S3 object storage bucket.

For this {deliverable}, you run a provided script that creates the following local S4 storage buckets for you:

* *My Storage* - Use this bucket for storing your models and data. You can reuse this bucket and its connection for your notebooks and model servers.
*  *Pipelines Artifacts* - Use this bucket as storage for your pipeline artifacts. When you create a pipeline server, you need a pipeline artifacts bucket. For this {deliverable}, create this bucket to separate it from the first storage bucket for clarity.

NOTE: Although you can use one storage bucket for both storing models and data and for storing pipeline artifacts, this {deliverable} follows the recommended practice of using separate storage buckets for each purpose.

The provided script also creates a connection to each storage bucket.

If you want to use your own S3-compatible object storage buckets, you can create connections to your own storage instead.

[role="_additional-resources"]
.Additional resources

* xref:running-a-script-to-install-storage.adoc[Run an automated script for local object storage]
* xref:creating-connections-to-storage.adoc[Create connections to your own S3-compatible object storage]

