---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-setup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demo-setup-edit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: demo-setup
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: s4
    app.kubernetes.io/component: storage
    app.kubernetes.io/instance: s4
    app.kubernetes.io/name: s4
    app.kubernetes.io/part-of: s4
    component: s4
  name: s4-config
data:
  AWS_DEFAULT_REGION: us-east-1
  AWS_S3_ENDPOINT: http://localhost:7480
  IP: 0.0.0.0
  JWT_EXPIRATION_HOURS: "8"
  LOCAL_STORAGE_PATHS: ""
  MAX_CONCURRENT_TRANSFERS: "2"
  MAX_FILE_SIZE_GB: "20"
  PORT: "5000"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: s4
    app.kubernetes.io/component: storage
    app.kubernetes.io/instance: s4
    app.kubernetes.io/name: s4
    app.kubernetes.io/part-of: s4
    component: s4
  name: s4
spec:
  ports:
  - name: s3-api
    port: 7480
    protocol: TCP
    targetPort: 7480
  - name: web-ui
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: s4
    app.kubernetes.io/component: storage
    app.kubernetes.io/instance: s4
    app.kubernetes.io/name: s4
    app.kubernetes.io/part-of: s4
    component: s4
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: s4
    app.kubernetes.io/component: storage
    app.kubernetes.io/instance: s4
    app.kubernetes.io/name: s4
    app.kubernetes.io/part-of: s4
    component: s4
  name: s4-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: s4
    app.kubernetes.io/component: storage
    app.kubernetes.io/instance: s4
    app.kubernetes.io/name: s4
    app.kubernetes.io/part-of: s4
    component: s4
  name: s4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s4
      app.kubernetes.io/component: storage
      app.kubernetes.io/instance: s4
      app.kubernetes.io/name: s4
      app.kubernetes.io/part-of: s4
      component: s4
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: s4
        app.kubernetes.io/component: storage
        app.kubernetes.io/instance: s4
        app.kubernetes.io/name: s4
        app.kubernetes.io/part-of: s4
        component: s4
    spec:
      containers:
        - envFrom:
          - configMapRef:
              name: s4-config
          - secretRef:
              name: s4-credentials
          image: quay.io/rh-aiservices-bu/s4:latest
          name: s4
          ports:
            - containerPort: 7480
              name: s3-api
              protocol: TCP
            - containerPort: 5000
              name: web-ui
              protocol: TCP
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: 250m
              memory: 512Mi
          volumeMounts:
            - mountPath: /var/lib/ceph/radosgw
              name: s4-data
      volumes:
        - name: s4-data
          persistentVolumeClaim:
            claimName: s4-data
---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-ds-connections
  labels:
    app: s4
    app.kubernetes.io/component: storage
    app.kubernetes.io/instance: s4
    app.kubernetes.io/name: s4
    app.kubernetes.io/part-of: s4
    component: s4
spec:
  selector: {}
  template:
    spec:
      initContainers:
        - args:
            - -ec
            - |-
              echo -n 'Waiting for s4-credentials secrets'
              while ! oc get secret s4-credentials 2>/dev/null | grep -qF s4-credentials; do
              echo -n .
              sleep 5
              done; echo

              echo -n 'Waiting for s4-api route'
              while ! oc get route s4-api 2>/dev/null | grep -qF s4; do
                echo -n .
                sleep 5
              done; echo

              echo -n 'Waiting for deployment to become available'
              oc wait --for=condition=available --timeout=60s deployment/s4
              sleep 3
          command:
            - /bin/bash
          image: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
          imagePullPolicy: IfNotPresent
          name: wait-for-s4
      containers:
        - args:
            - -ec
            - |-
              S4_HOST=https://$(oc get route s4-api -o template --template '{{.spec.host}}')
              AWS_ACCESS_KEY_ID=$(oc get secret s4-credentials -o template --template '{{.data.AWS_ACCESS_KEY_ID}}')
              AWS_SECRET_ACCESS_KEY=$(oc get secret s4-credentials -o template --template '{{.data.AWS_SECRET_ACCESS_KEY}}')

              cat << EOF | oc apply -f-
              apiVersion: v1
              kind: Secret
              metadata:
                annotations:
                  opendatahub.io/connection-type: s3
                  openshift.io/display-name: My Storage
                labels:
                  opendatahub.io/dashboard: "true"
                  opendatahub.io/managed: "true"
                name: my-storage
              data:
                AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
                AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
              stringData:
                AWS_DEFAULT_REGION: us-east-1
                AWS_S3_BUCKET: my-storage
                AWS_S3_ENDPOINT: ${S4_HOST}
              type: Opaque
              EOF
              cat << EOF | oc apply -f-
              apiVersion: v1
              kind: Secret
              metadata:
                annotations:
                  opendatahub.io/connection-type: s3
                  openshift.io/display-name: Pipeline Artifacts
                labels:
                  opendatahub.io/dashboard: "true"
                  opendatahub.io/managed: "true"
                name: pipeline-artifacts
              data:
                AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
                AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
              stringData:
                AWS_DEFAULT_REGION: us-east-1
                AWS_S3_BUCKET: pipeline-artifacts
                AWS_S3_ENDPOINT: ${S4_HOST}
              type: Opaque
              EOF
          command:
            - /bin/bash
          image: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
          imagePullPolicy: IfNotPresent
          name: create-ds-connections
      restartPolicy: Never
      serviceAccount: demo-setup
      serviceAccountName: demo-setup
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: s4
    app.kubernetes.io/component: storage
    app.kubernetes.io/instance: s4
    app.kubernetes.io/name: s4
    app.kubernetes.io/part-of: s4
    component: s4
  name: create-s4-buckets
spec:
  selector: {}
  template:
    metadata:
      labels:
        app: s4
        app.kubernetes.io/component: storage
        app.kubernetes.io/instance: s4
        app.kubernetes.io/name: s4
        app.kubernetes.io/part-of: s4
        component: s4
    spec:
      containers:
        - args:
            - -ec
            - |-
              oc get secret s4-credentials
              cat << 'EOF' | python3
              import boto3, os

              s3 = boto3.client("s3",
                                endpoint_url="http://s4:7480",
                                aws_access_key_id=os.getenv("AWS_ACCESS_KEY_ID"),
                                aws_secret_access_key=os.getenv("AWS_SECRET_ACCESS_KEY"))
              bucket = 'pipeline-artifacts'
              print('creating pipeline-artifacts bucket')
              if bucket not in [bu["Name"] for bu in s3.list_buckets()["Buckets"]]:
                s3.create_bucket(Bucket=bucket)
              bucket = 'my-storage'
              print('creating my-storage bucket')
              if bucket not in [bu["Name"] for bu in s3.list_buckets()["Buckets"]]:
                s3.create_bucket(Bucket=bucket)
              EOF
          command:
            - /bin/bash
          envFrom:
            - secretRef:
                name: s4-credentials
          image: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/s2i-generic-data-science-notebook:2024.1
          imagePullPolicy: IfNotPresent
          name: create-buckets
      initContainers:
        - args:
            - -ec
            - |-
              echo -n 'Waiting for s4-credentials secrets'
              while ! oc get secret s4-credentials 2>/dev/null | grep -qF s4-credentials; do
              echo -n .
              sleep 5
              done; echo

              echo -n 'Waiting for s4 deployment'
              while ! oc get deployment s4 2>/dev/null | grep -qF s4; do
                echo -n .
                sleep 5
              done; echo
              oc wait --for=condition=available --timeout=60s deployment/s4
              sleep 10
          command:
            - /bin/bash
          image: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
          imagePullPolicy: IfNotPresent
          name: wait-for-s4
      restartPolicy: Never
      serviceAccount: demo-setup
      serviceAccountName: demo-setup
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: s4
    app.kubernetes.io/component: storage
    app.kubernetes.io/instance: s4
    app.kubernetes.io/name: s4
    app.kubernetes.io/part-of: s4
    component: s4
  name: create-s4-credentials-secret
spec:
  backoffLimit: 4
  template:
    metadata:
      labels:
        app: s4
        app.kubernetes.io/component: storage
        app.kubernetes.io/instance: s4
        app.kubernetes.io/name: s4
        app.kubernetes.io/part-of: s4
        component: s4
    spec:
      containers:
        - args:
            - -ec
            - |-
              if [ -n "$(oc get secret s4-credentials -oname 2>/dev/null)" ]; then
                echo "Secret already exists. Skipping." >&2
                exit 0
              fi
              genpass() {
                  < /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c"${1:-32}"
              }
              ui_id=$(genpass 16)
              ui_secret=$(genpass)
              aws_accesskeyid=$(genpass 16)
              aws_secretaccesskey=$(genpass)
              cat << EOF | oc apply -f-
              apiVersion: v1
              kind: Secret
              metadata:
                name: s4-credentials
              type: Opaque
              stringData:
                UI_USERNAME: ${ui_id}
                UI_PASSWORD: ${ui_secret}
                AWS_ACCESS_KEY_ID: ${aws_accesskeyid}
                AWS_SECRET_ACCESS_KEY: ${aws_secretaccesskey}
              EOF
          command:
            - /bin/bash
          image: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
          imagePullPolicy: IfNotPresent
          name: create-s4-credentials-secret
      restartPolicy: Never
      serviceAccount: demo-setup
      serviceAccountName: demo-setup
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: s4
    app.kubernetes.io/component: storage
    app.kubernetes.io/instance: s4
    app.kubernetes.io/name: s4
    app.kubernetes.io/part-of: s4
    component: s4
  name: s4
spec:
  port:
    targetPort: web-ui
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: s4
    weight: 100
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: s4
    app.kubernetes.io/component: storage
    app.kubernetes.io/instance: s4
    app.kubernetes.io/name: s4
    app.kubernetes.io/part-of: s4
    component: s4
  name: s4-api
spec:
  port:
    targetPort: s3-api
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: s4
    weight: 100
  wildcardPolicy: None
